### ISSUE TITLE
MythTV fails to build with libva 2.18.0

### ISSUE THREAD

**Issue by gigem** [MythTV/mythtv#765]
* **Platform**: Debian Testing

* **MythTV version**: Master

* **Package version**: N/A

* **Component**: MythTV

### What do you see instead?  

libavcodec/x86/mathops.h: Assembler messages:                                   
libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'            
libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'            
libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'            
make[2]: *** [ffbuild/common.mak:81: libavcodec/vaapi_mpeg2.o] Error 1          
make[2]: Leaving directory '/home/david/src/mythtv/master/mythtv/external/FFmpe\
g'                                                                              
make[1]: *** [Makefile:32: FFmpeg-all] Error 2                                  
make[1]: Leaving directory '/home/david/src/mythtv/master/mythtv/external'      
make: *** [Makefile:66: external] Error 2

**Comment by gigem** [comment]
A fix used by other projects is to not define NEG_SSR32 and NEG_USR32 in libavcodec/x86/mathops.h.  I'm still not sure why libva 2.18 is causing this to show up.

**Comment by garybuhrmaster** [comment]
> A fix used by other projects is to not define NEG_SSR32 and NEG_USR32 in libavcodec/x86/mathops.h. I'm still not sure why libva 2.18 is causing this to show up.

May be something debian specific, as it works on Fedora F38 which has libva 2.18.0.

As the error message is from gas, it is likely a binutils update which is causing the issue.

Searching the binutils bug tracker, I find this:  https://sourceware.org/bugzilla/show_bug.cgi?id=30578

**Comment by gigem** [comment]
Good point on binutils.  Downgrading to binutils 2.40-2 "fixes" the problem.  If you have access to binutils 2.40.50-*, please try to reproduce the problem with it.  I'm not familiar enough with gas to know if it's a bug or a tightening of requirements.

Also, there is still some funny business going on that simply upgrading libvav or adding #if 1 triggers it.  Hmm, it just occurred to me that that could all be explained by ccache -- the preprocessed C is the same as before so the object code should be too.

**Comment by gigem** [comment]
ccache is definitely the cause of the weirdness.  Now, back to binutils

**Comment by garybuhrmaster** [comment]
> Good point on binutils. Downgrading to binutils 2.40-2 "fixes" the problem. If you have access to binutils 2.40.50-*, please try to reproduce the problem with it.

Without building my own binutils from the upstream repo at a recent commit (which I really don't want to do at the moment), 2.40 is the latest I easily have available.  Given the bug report, others have encountered this too, so another reproducer is probably not useful.

> I'm not familiar enough with gas to know if it's a bug or a tightening of requirements.

The bug report indicates that the commit to restrict to positive values was intentional.  However, if I am reading correctly, the hardware implementations masks the resulting shift amount before the shift/rotate, so in theory the instruction execution supports an immediate value which is negative.

I am sure one of the gcc/gas/ffmpeg teams will decide who has to address the issue.  You can always add yourself to the binutils bug if you want to follow along.

**Comment by gigem** [comment]
It seems the logical thing to do is to conform to what the binutils developer wants.  The trouble is, I have no idea what that really is.  I've yet to sumble upon any acceptable cast or data type.

**Comment by marillat** [comment]
A bug has been filed against binutils for that;
https://sourceware.org/bugzilla/show_bug.cgi?id=30578

**Comment by marillat** [comment]
It is possible to have a MythTV 31 dot release from time to time ?
