### ISSUE TITLE
branch-fixes/34 doesn't compile with libx265 v4

### ISSUE THREAD

**Issue by hamelg** [MythTV/mythtv#966]
* **Platform**:
a uptodate Archlinux
* **MythTV version**:
34
* **Package version**:
mythtv-git 34.0.r30.gc376437559-1

When building mythv, the compilation fails with this error :

```
libavcodec/libx265.c: In function ‘libx265_encode_frame’:
libavcodec/libx265.c:579:59: error: passing argument 5 of ‘ctx->api->encoder_encode’ from incompatible pointer type [-Wincompatible-pointer-types]
  579 |                                    pic ? &x265pic : NULL, &x265pic_out);
      |                                                           ^~~~~~~~~~~~
      |                                                           |
      |                                                           x265_picture *
libavcodec/libx265.c:579:59: note: expected ‘x265_picture **’ but argument is of type ‘x265_picture *’
CC      libavcodec/mjpegbdec.o
make[2]: *** [ffbuild/common.mak:81: libavcodec/libx265.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/goinfre/build/arch/mythtv-git/src/mythtv/mythtv/external/FFmpeg'
make[1]: *** [Makefile:32: FFmpeg-all] Error 2
make[1]: Leaving directory '/goinfre/build/arch/mythtv-git/src/mythtv/mythtv/external'
make: *** [Makefile:66: external] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

```

**Comment by hamelg** [comment]
This error occurs after upgrading libx265 dependency from 3.6 to 4.0.

**Comment by ulmus-scott** [comment]
I suspect you will need https://github.com/FFmpeg/FFmpeg/commit/1f801dfdb5066aadf0ade9cb5e94d620f33eacdc and https://github.com/FFmpeg/FFmpeg/commit/099f88b8641dfc299f3896d17d9addc5b9ae7799

**Comment by hamelg** [comment]
thanks !
at now we use libx265.so.212, [FFmpeg/FFmpeg@1f801df](https://github.com/FFmpeg/FFmpeg/commit/1f801dfdb5066aadf0ade9cb5e94d620f33eacdc) should be enough.

**Comment by ulmus-scott** [comment]
The FFmpeg commits were added to fixes/34, so please close this issue if it has been resolved.

**Comment by hamelg** [comment]
I confirm, this issue is fixed. Thanks.
