### ISSUE TITLE
master does not build on macOS High Sierra

### ISSUE THREAD

**Issue by jhoyt4** [MythTV/mythtv#285]
* **Platform**: macOS 10.13.6 - High Sierra

* **MythTV version**: master - head

* **Package version**:

* **Component**: libmyth/mediamonitor-darwin.cpp

### What steps will reproduce the bug?

Unable to compile on macOS 10.13 without the following patch due to variable names having incorrect character cases

### How often does it reproduce? Is there a required condition?

fails to compile every time on 10.13 with errors on mediamonitor-darwin.cpp

[compile_log.txt](https://github.com/MythTV/mythtv/files/5580769/compile_log.txt)

### What is the expected behaviour?

successful compile like on macOS 10.15.7 :)

### What do you see instead?

> mediamonitor-darwin.cpp:395:12: error: use of undeclared identifier 'm_Monitor'
    while (m_Monitor && m_Monitor->IsActive())
           ^
mediamonitor-darwin.cpp:395:25: error: use of undeclared identifier 'm_Monitor'; did you mean 'm_monitor'?
    while (m_Monitor && m_Monitor->IsActive())
                        ^~~~~~~~~
                        m_monitor
./mythmediamonitor.h:38:28: note: 'm_monitor' declared here
    QPointer<MediaMonitor> m_monitor;
                           ^
mediamonitor-darwin.cpp:400:36: error: use of undeclared identifier 'm_Interval'
                           (float) m_Interval / 1000.0F, false );
                                   ^
mediamonitor-darwin.cpp:427:56: error: use of undeclared identifier 'm_Monitor'; did you mean 'm_monitor'?
        media = MythCDROM::get(nullptr, devName, true, m_Monitor->m_AllowEject);
                                                       ^~~~~~~~~
                                                       m_monitor
./mythmediamonitor.h:38:28: note: 'm_monitor' declared here
    QPointer<MediaMonitor> m_monitor;
                           ^
mediamonitor-darwin.cpp:466:9: error: use of undeclared identifier 'm_Monitor'
    if (m_Monitor->shouldIgnore(media))
        ^
mediamonitor-darwin.cpp:474:5: error: use of undeclared identifier 'm_Monitor'; did you mean 'm_monitor'?
    m_Monitor->AddDevice(media);
    ^~~~~~~~~
    m_monitor
./mythmediamonitor.h:38:28: note: 'm_monitor' declared here
    QPointer<MediaMonitor> m_monitor;
                           ^
mediamonitor-darwin.cpp:482:32: error: use of undeclared identifier 'm_Monitor'; did you mean 'm_monitor'?
    MythMediaDevice *pDevice = m_Monitor->GetMedia(devName);
                               ^~~~~~~~~
                               m_monitor
./mythmediamonitor.h:38:28: note: 'm_monitor' declared here
    QPointer<MediaMonitor> m_monitor;
                           ^
mediamonitor-darwin.cpp:489:5: error: use of undeclared identifier 'm_Monitor'; did you mean 'm_monitor'?
    m_Monitor->RemoveDevice(devName);
    ^~~~~~~~~
    m_monitor
./mythmediamonitor.h:38:28: note: 'm_monitor' declared here
    QPointer<MediaMonitor> m_monitor;
                           ^
mediamonitor-darwin.cpp:504:32: error: use of undeclared identifier 'm_Monitor'; did you mean 'm_monitor'?
    MythMediaDevice *pDevice = m_Monitor->GetMedia(devName);
                               ^~~~~~~~~
                               m_monitor
./mythmediamonitor.h:38:28: note: 'm_monitor' declared here
    QPointer<MediaMonitor> m_monitor;
                           ^
mediamonitor-darwin.cpp:506:9: error: use of undeclared identifier 'm_Monitor'
    if (m_Monitor->ValidateAndLock(pDevice))
        ^
mediamonitor-darwin.cpp:517:9: error: use of undeclared identifier 'm_Monitor'; did you mean 'm_monitor'?
        m_Monitor->Unlock(pDevice);
        ^~~~~~~~~
        m_monitor
./mythmediamonitor.h:38:28: note: 'm_monitor' declared here
    QPointer<MediaMonitor> m_monitor;
                           ^
mediamonitor-darwin.cpp:533:9: error: use of undeclared identifier 'm_Active'
    if (m_Active)
        ^
mediamonitor-darwin.cpp:539:5: error: use of undeclared identifier 'm_Devices'; did you mean 'm_devices'?
    m_Devices.clear();
    ^~~~~~~~~
    m_devices
./mythmediamonitor.h:117:34: note: 'm_devices' declared here
    QList<MythMediaDevice*>      m_devices;
                                 ^
mediamonitor-darwin.cpp:542:10: error: use of undeclared identifier 'm_Thread'; did you mean 'm_thread'?
    if (!m_Thread)
         ^~~~~~~~
         m_thread
./mythmediamonitor.h:126:34: note: 'm_thread' declared here
    MonitorThread               *m_thread {nullptr};
                                 ^
mediamonitor-darwin.cpp:543:9: error: use of undeclared identifier 'm_Thread'; did you mean 'm_thread'?
        m_Thread = new MonitorThreadDarwin(this, m_MonitorPollingInterval);
        ^~~~~~~~
        m_thread
./mythmediamonitor.h:126:34: note: 'm_thread' declared here
    MonitorThread               *m_thread {nullptr};
                                 ^
mediamonitor-darwin.cpp:543:50: error: use of undeclared identifier 'm_MonitorPollingInterval'; did you mean 'm_monitorPollingInterval'?
        m_Thread = new MonitorThreadDarwin(this, m_MonitorPollingInterval);
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~
                                                 m_monitorPollingInterval
./mythmediamonitor.h:127:34: note: 'm_monitorPollingInterval' declared here
    unsigned long                m_monitorPollingInterval;
                                 ^
mediamonitor-darwin.cpp:548:5: error: use of undeclared identifier 'm_Active'; did you mean 'm_active'?
    m_Active = true;
    ^~~~~~~~
    m_active
./mythmediamonitor.h:124:34: note: 'm_active' declared here
    bool volatile                m_active {false};      ///< Was MonitorThread started?
                                 ^
mediamonitor-darwin.cpp:549:5: error: use of undeclared identifier 'm_Thread'; did you mean 'm_thread'?
    m_Thread->start();
    ^~~~~~~~
    m_thread
./mythmediamonitor.h:126:34: note: 'm_thread' declared here
    MonitorThread               *m_thread {nullptr};
                                 ^
mediamonitor-darwin.cpp:569:5: error: use of undeclared identifier 'm_Devices'; did you mean 'm_devices'?
    m_Devices.push_back( pDevice );
    ^~~~~~~~~
    m_devices
./mythmediamonitor.h:117:34: note: 'm_devices' declared here
    QList<MythMediaDevice*>      m_devices;
                                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [obj/mediamonitor-darwin.o] Error 1
make[1]: *** [sub-libmyth-make_first] Error 2
make: *** [libs] Error 2
    Compiling Mythtv failed

### Additional information

successfully complies (and tested) on 10.13.6 with the following patch:

[highsierra.patch.diff.txt](https://github.com/MythTV/mythtv/files/5580752/highsierra.patch.diff.txt)

- Patch successfully tested on Catalina

**Comment by jhoyt4** [comment]
I've just finished testing the patch on HS and Catalina - everything seems to be in order (updated the initial issue post to reflect the change in testing status)

**Comment by jhoyt4** [comment]
Added a pull request here [https://github.com/MythTV/mythtv/pull/286](url)
